name: Run FastAPI Tests

on:
  push:
    branches:
      - test-afaqahmad

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run Docker containers
      run: docker-compose up --build --abort-on-container-exit

    - name: Run tests
      run: docker-compose run test
